// SPDX-FileCopyrightText: 2026 ChipDesign B.V.
// SPDX-License-Identifier: Apache-2.0
//
// cdriscv-32s-10 FULL-CHIP top: cdriscv_subsys wrapped in an IHP
// SG13G2 IO pad ring (sg13g2_io library).  GENERATED by
// scripts/gen_padring.py -- edit the generator, not this file.
//
// THIS CHIP CONTAINS NO ADC.  All AMS interface signals (adc_*, dac_*,
// atest_*, ana_flag_*) go to pads on the WEST side (DAC bundle on the
// adjacent north-west corner) for an external analog companion die.
//
// THIS CHIP HAS NO JTAG.  Variant 1's subsystem does not carry the
// debug TAP, so the four JTAG input pads and the tri-state TDO pad of
// variant 2 are absent -- the only pad-count difference from variant 2.
//
// FLASH BOOT: cdriscv_subsys is instantiated with BootEnable=1 (its
// default is 0 -- the signed-off, TCM-preloaded configuration), so the
// QSPI boot loader is elaborated and its five ports reach pads.  The
// chip IS the hard top: cdriscv_subsys is instantiated directly with
// boot_addr_i tied to 32'h0000_0000, mirroring
// flow/cdriscv_subsys_hard.sv (finding V18: a non-constant PC reset
// load is an async-load flop no standard cell implements).
//
// NOT PADDED (documented decision, not an omission):
//   * SoC expansion APB (ext_p*, 78 wires): unused on this die.  Inputs
//     tied benign (ext_pready_i=1 so a stray access completes,
//     ext_pslverr_i=0, ext_prdata_i=0); outputs unconnected.
//   * Retire trace (retire_*, 66 wires): verification-only interface.
//     Outputs unconnected.
//
// QSPI boot flash: four sg13g2_IOPadInOut4mA data pads expose ONE chip
// inout bus qspi_io[3:0]; per bit c2p = qspi_io_o, p2c = qspi_io_i,
// c2p_en = qspi_io_oe_o (the pad model implements
//   assign pad = c2p_en ? c2p : 1'bz;
// plus the p2c input path).  The loader drives io_oe per SPI phase; in
// quad data phases all four lines are flash-driven inputs.  Grouped with
// qspi_sclk_o / qspi_cs_no beside the south-east corner.
//
// Die 2400 x 3500 um, 100 pads + 4 corners.
// Pad numbering runs counter-clockwise from the south-west corner;
// per-side positions ascend west->east (S, N) and south->north (E, W).
//
// pad  pos  chip net          cell                    drive
// ---  ---  ----------------  ----------------------  -----
//   1  S01  (pad ring)        sg13g2_IOPadIOVss       -
//   2  S02  (pad ring)        sg13g2_IOPadIOVdd       -
//   3  S03  (pad ring)        sg13g2_IOPadVdd         -
//   4  S04  (pad ring)        sg13g2_IOPadVss         -
//   5  S05  clk_i             sg13g2_IOPadIn          -
//   6  S06  rst_ni            sg13g2_IOPadIn          -
//   7  S07  fetch_enable_i    sg13g2_IOPadIn          -
//   8  S08  err_pin_o         sg13g2_IOPadOut4mA      4 mA
//   9  S09  reset_req_o       sg13g2_IOPadOut4mA      4 mA
//  10  S10  fault_any_o       sg13g2_IOPadOut4mA      4 mA
//  11  S11  core_sleep_o      sg13g2_IOPadOut4mA      4 mA
//  12  S12  qspi_sclk_o       sg13g2_IOPadOut4mA      4 mA
//  13  S13  qspi_cs_no        sg13g2_IOPadOut4mA      4 mA
//  14  S14  qspi_io[0]        sg13g2_IOPadInOut4mA    4 mA
//  15  S15  qspi_io[1]        sg13g2_IOPadInOut4mA    4 mA
//  16  S16  qspi_io[2]        sg13g2_IOPadInOut4mA    4 mA
//  17  S17  qspi_io[3]        sg13g2_IOPadInOut4mA    4 mA
//  18  E01  fault_ext_i[0]    sg13g2_IOPadIn          -
//  19  E02  fault_ext_i[1]    sg13g2_IOPadIn          -
//  20  E03  fault_ext_i[2]    sg13g2_IOPadIn          -
//  21  E04  fault_ext_i[3]    sg13g2_IOPadIn          -
//  22  E05  fault_ext_i[4]    sg13g2_IOPadIn          -
//  23  E06  fault_ext_i[5]    sg13g2_IOPadIn          -
//  24  E07  fault_ext_i[6]    sg13g2_IOPadIn          -
//  25  E08  fault_ext_i[7]    sg13g2_IOPadIn          -
//  26  E09  fault_ext_i[8]    sg13g2_IOPadIn          -
//  27  E10  fault_ext_i[9]    sg13g2_IOPadIn          -
//  28  E11  fault_ext_i[10]   sg13g2_IOPadIn          -
//  29  E12  fault_ext_i[11]   sg13g2_IOPadIn          -
//  30  E13  fault_ext_i[12]   sg13g2_IOPadIn          -
//  31  E14  fault_ext_i[13]   sg13g2_IOPadIn          -
//  32  E15  fault_ext_i[14]   sg13g2_IOPadIn          -
//  33  E16  fault_ext_i[15]   sg13g2_IOPadIn          -
//  34  E17  (pad ring)        sg13g2_IOPadVdd         -
//  35  E18  (pad ring)        sg13g2_IOPadVss         -
//  36  E19  (pad ring)        sg13g2_IOPadIOVdd       -
//  37  E20  (pad ring)        sg13g2_IOPadIOVss       -
//  38  E21  irq_i[0]          sg13g2_IOPadIn          -
//  39  E22  irq_i[1]          sg13g2_IOPadIn          -
//  40  E23  irq_i[2]          sg13g2_IOPadIn          -
//  41  E24  irq_i[3]          sg13g2_IOPadIn          -
//  42  E25  irq_i[4]          sg13g2_IOPadIn          -
//  43  E26  irq_i[5]          sg13g2_IOPadIn          -
//  44  E27  irq_i[6]          sg13g2_IOPadIn          -
//  45  E28  irq_i[7]          sg13g2_IOPadIn          -
//  46  E29  irq_i[8]          sg13g2_IOPadIn          -
//  47  E30  irq_i[9]          sg13g2_IOPadIn          -
//  48  E31  irq_i[10]         sg13g2_IOPadIn          -
//  49  E32  irq_i[11]         sg13g2_IOPadIn          -
//  50  E33  irq_i[12]         sg13g2_IOPadIn          -
//  51  E34  irq_i[13]         sg13g2_IOPadIn          -
//  52  N01  dac_we_o          sg13g2_IOPadOut4mA      4 mA
//  53  N02  dac_data_o[0]     sg13g2_IOPadOut4mA      4 mA
//  54  N03  dac_data_o[1]     sg13g2_IOPadOut4mA      4 mA
//  55  N04  dac_data_o[2]     sg13g2_IOPadOut4mA      4 mA
//  56  N05  dac_data_o[3]     sg13g2_IOPadOut4mA      4 mA
//  57  N06  dac_data_o[4]     sg13g2_IOPadOut4mA      4 mA
//  58  N07  dac_data_o[5]     sg13g2_IOPadOut4mA      4 mA
//  59  N08  dac_data_o[6]     sg13g2_IOPadOut4mA      4 mA
//  60  N09  dac_data_o[7]     sg13g2_IOPadOut4mA      4 mA
//  61  N10  dac_data_o[8]     sg13g2_IOPadOut4mA      4 mA
//  62  N11  dac_data_o[9]     sg13g2_IOPadOut4mA      4 mA
//  63  N12  dac_data_o[10]    sg13g2_IOPadOut4mA      4 mA
//  64  N13  dac_data_o[11]    sg13g2_IOPadOut4mA      4 mA
//  65  N14  (pad ring)        sg13g2_IOPadVdd         -
//  66  N15  (pad ring)        sg13g2_IOPadVss         -
//  67  N16  (pad ring)        sg13g2_IOPadIOVdd       -
//  68  N17  (pad ring)        sg13g2_IOPadIOVss       -
//  69  N18  ref_clk_i         sg13g2_IOPadIn          -
//  70  N19  ref_rst_ni        sg13g2_IOPadIn          -
//  71  W01  atest_en_o        sg13g2_IOPadOut4mA      4 mA
//  72  W02  atest_sel_o[0]    sg13g2_IOPadOut4mA      4 mA
//  73  W03  atest_sel_o[1]    sg13g2_IOPadOut4mA      4 mA
//  74  W04  atest_sel_o[2]    sg13g2_IOPadOut4mA      4 mA
//  75  W05  atest_sel_o[3]    sg13g2_IOPadOut4mA      4 mA
//  76  W06  ana_flag_i[0]     sg13g2_IOPadIn          -
//  77  W07  ana_flag_i[1]     sg13g2_IOPadIn          -
//  78  W08  ana_flag_i[2]     sg13g2_IOPadIn          -
//  79  W09  ana_flag_i[3]     sg13g2_IOPadIn          -
//  80  W10  (pad ring)        sg13g2_IOPadVdd         -
//  81  W11  (pad ring)        sg13g2_IOPadVss         -
//  82  W12  adc_start_o       sg13g2_IOPadOut4mA      4 mA
//  83  W13  adc_ch_o[0]       sg13g2_IOPadOut4mA      4 mA
//  84  W14  adc_ch_o[1]       sg13g2_IOPadOut4mA      4 mA
//  85  W15  adc_ch_o[2]       sg13g2_IOPadOut4mA      4 mA
//  86  W16  adc_valid_i       sg13g2_IOPadIn          -
//  87  W17  adc_data_i[0]     sg13g2_IOPadIn          -
//  88  W18  adc_data_i[1]     sg13g2_IOPadIn          -
//  89  W19  adc_data_i[2]     sg13g2_IOPadIn          -
//  90  W20  adc_data_i[3]     sg13g2_IOPadIn          -
//  91  W21  adc_data_i[4]     sg13g2_IOPadIn          -
//  92  W22  adc_data_i[5]     sg13g2_IOPadIn          -
//  93  W23  adc_data_i[6]     sg13g2_IOPadIn          -
//  94  W24  adc_data_i[7]     sg13g2_IOPadIn          -
//  95  W25  adc_data_i[8]     sg13g2_IOPadIn          -
//  96  W26  adc_data_i[9]     sg13g2_IOPadIn          -
//  97  W27  adc_data_i[10]    sg13g2_IOPadIn          -
//  98  W28  adc_data_i[11]    sg13g2_IOPadIn          -
//  99  W29  (pad ring)        sg13g2_IOPadIOVdd       -
// 100  W30  (pad ring)        sg13g2_IOPadIOVss       -
//
// Power pads (one quad VDD/VSS core 1.2 V + IOVDD/IOVSS pad-ring 3.3 V per
// side, 16 total): supply-only cells with no logic terminals.  Their supply
// nets connect by ring abutment in layout (OpenROAD connect_by_abutment);
// in this netlist they are instance shells kept alive by (* keep *).
//
// NO pad instance references its vdd/vss/iovdd/iovss supply ports: the
// liberty view librelane hands to synthesis as the blackbox has no such
// ports (supplies are pg_pins), so naming them is an elaboration error
// there, while leaving them unconnected is correct everywhere.
`default_nettype none
module cdriscv_chip (
    input  wire clk_i,
    input  wire rst_ni,
    input  wire ref_clk_i,
    input  wire ref_rst_ni,
    input  wire fetch_enable_i,
    input  wire [13:0] irq_i,
    input  wire [15:0] fault_ext_i,
    output wire err_pin_o,
    output wire reset_req_o,
    output wire fault_any_o,
    output wire adc_start_o,
    output wire [2:0] adc_ch_o,
    input  wire adc_valid_i,
    input  wire [11:0] adc_data_i,
    output wire [11:0] dac_data_o,
    output wire dac_we_o,
    output wire atest_en_o,
    output wire [3:0] atest_sel_o,
    input  wire [3:0] ana_flag_i,
    output wire core_sleep_o,
    output wire qspi_sclk_o,
    output wire qspi_cs_no,
    inout  wire [3:0] qspi_io
);

  // core-side nets (pad p2c/c2p terminals)
  wire clk_i_core;
  wire rst_ni_core;
  wire ref_clk_i_core;
  wire ref_rst_ni_core;
  wire fetch_enable_i_core;
  wire [13:0] irq_i_core;
  wire [15:0] fault_ext_i_core;
  wire err_pin_o_core;
  wire reset_req_o_core;
  wire fault_any_o_core;
  wire adc_start_o_core;
  wire [2:0] adc_ch_o_core;
  wire adc_valid_i_core;
  wire [11:0] adc_data_i_core;
  wire [11:0] dac_data_o_core;
  wire dac_we_o_core;
  wire atest_en_o_core;
  wire [3:0] atest_sel_o_core;
  wire [3:0] ana_flag_i_core;
  wire core_sleep_o_core;
  wire qspi_sclk_o_core;
  wire qspi_cs_no_core;
  wire [3:0] qspi_io_i_core;
  wire [3:0] qspi_io_o_core;
  wire [3:0] qspi_io_oe_o_core;

  // ---- SOUTH row (listed west->east / south->north) ----
  (* keep *) sg13g2_IOPadIOVss pad_iovss_s ();
  (* keep *) sg13g2_IOPadIOVdd pad_iovdd_s ();
  (* keep *) sg13g2_IOPadVdd pad_vdd_s ();
  (* keep *) sg13g2_IOPadVss pad_vss_s ();
  (* keep *) sg13g2_IOPadIn pad_clk_i (.pad(clk_i), .p2c(clk_i_core));
  (* keep *) sg13g2_IOPadIn pad_rst_ni (.pad(rst_ni), .p2c(rst_ni_core));
  (* keep *) sg13g2_IOPadIn pad_fetch_enable_i (.pad(fetch_enable_i), .p2c(fetch_enable_i_core));
  (* keep *) sg13g2_IOPadOut4mA pad_err_pin_o (.pad(err_pin_o), .c2p(err_pin_o_core));
  (* keep *) sg13g2_IOPadOut4mA pad_reset_req_o (.pad(reset_req_o), .c2p(reset_req_o_core));
  (* keep *) sg13g2_IOPadOut4mA pad_fault_any_o (.pad(fault_any_o), .c2p(fault_any_o_core));
  (* keep *) sg13g2_IOPadOut4mA pad_core_sleep_o (.pad(core_sleep_o), .c2p(core_sleep_o_core));
  (* keep *) sg13g2_IOPadOut4mA pad_qspi_sclk_o (.pad(qspi_sclk_o), .c2p(qspi_sclk_o_core));
  (* keep *) sg13g2_IOPadOut4mA pad_qspi_cs_no (.pad(qspi_cs_no), .c2p(qspi_cs_no_core));
  (* keep *) sg13g2_IOPadInOut4mA pad_qspi_io_0 (.pad(qspi_io[0]), .c2p(qspi_io_o_core[0]), .p2c(qspi_io_i_core[0]), .c2p_en(qspi_io_oe_o_core[0]));
  (* keep *) sg13g2_IOPadInOut4mA pad_qspi_io_1 (.pad(qspi_io[1]), .c2p(qspi_io_o_core[1]), .p2c(qspi_io_i_core[1]), .c2p_en(qspi_io_oe_o_core[1]));
  (* keep *) sg13g2_IOPadInOut4mA pad_qspi_io_2 (.pad(qspi_io[2]), .c2p(qspi_io_o_core[2]), .p2c(qspi_io_i_core[2]), .c2p_en(qspi_io_oe_o_core[2]));
  (* keep *) sg13g2_IOPadInOut4mA pad_qspi_io_3 (.pad(qspi_io[3]), .c2p(qspi_io_o_core[3]), .p2c(qspi_io_i_core[3]), .c2p_en(qspi_io_oe_o_core[3]));
  // ---- EAST row (listed west->east / south->north) ----
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_0 (.pad(fault_ext_i[0]), .p2c(fault_ext_i_core[0]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_1 (.pad(fault_ext_i[1]), .p2c(fault_ext_i_core[1]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_2 (.pad(fault_ext_i[2]), .p2c(fault_ext_i_core[2]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_3 (.pad(fault_ext_i[3]), .p2c(fault_ext_i_core[3]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_4 (.pad(fault_ext_i[4]), .p2c(fault_ext_i_core[4]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_5 (.pad(fault_ext_i[5]), .p2c(fault_ext_i_core[5]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_6 (.pad(fault_ext_i[6]), .p2c(fault_ext_i_core[6]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_7 (.pad(fault_ext_i[7]), .p2c(fault_ext_i_core[7]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_8 (.pad(fault_ext_i[8]), .p2c(fault_ext_i_core[8]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_9 (.pad(fault_ext_i[9]), .p2c(fault_ext_i_core[9]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_10 (.pad(fault_ext_i[10]), .p2c(fault_ext_i_core[10]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_11 (.pad(fault_ext_i[11]), .p2c(fault_ext_i_core[11]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_12 (.pad(fault_ext_i[12]), .p2c(fault_ext_i_core[12]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_13 (.pad(fault_ext_i[13]), .p2c(fault_ext_i_core[13]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_14 (.pad(fault_ext_i[14]), .p2c(fault_ext_i_core[14]));
  (* keep *) sg13g2_IOPadIn pad_fault_ext_i_15 (.pad(fault_ext_i[15]), .p2c(fault_ext_i_core[15]));
  (* keep *) sg13g2_IOPadVdd pad_vdd_e ();
  (* keep *) sg13g2_IOPadVss pad_vss_e ();
  (* keep *) sg13g2_IOPadIOVdd pad_iovdd_e ();
  (* keep *) sg13g2_IOPadIOVss pad_iovss_e ();
  (* keep *) sg13g2_IOPadIn pad_irq_i_0 (.pad(irq_i[0]), .p2c(irq_i_core[0]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_1 (.pad(irq_i[1]), .p2c(irq_i_core[1]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_2 (.pad(irq_i[2]), .p2c(irq_i_core[2]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_3 (.pad(irq_i[3]), .p2c(irq_i_core[3]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_4 (.pad(irq_i[4]), .p2c(irq_i_core[4]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_5 (.pad(irq_i[5]), .p2c(irq_i_core[5]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_6 (.pad(irq_i[6]), .p2c(irq_i_core[6]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_7 (.pad(irq_i[7]), .p2c(irq_i_core[7]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_8 (.pad(irq_i[8]), .p2c(irq_i_core[8]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_9 (.pad(irq_i[9]), .p2c(irq_i_core[9]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_10 (.pad(irq_i[10]), .p2c(irq_i_core[10]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_11 (.pad(irq_i[11]), .p2c(irq_i_core[11]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_12 (.pad(irq_i[12]), .p2c(irq_i_core[12]));
  (* keep *) sg13g2_IOPadIn pad_irq_i_13 (.pad(irq_i[13]), .p2c(irq_i_core[13]));
  // ---- NORTH row (listed west->east / south->north) ----
  (* keep *) sg13g2_IOPadOut4mA pad_dac_we_o (.pad(dac_we_o), .c2p(dac_we_o_core));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_0 (.pad(dac_data_o[0]), .c2p(dac_data_o_core[0]));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_1 (.pad(dac_data_o[1]), .c2p(dac_data_o_core[1]));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_2 (.pad(dac_data_o[2]), .c2p(dac_data_o_core[2]));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_3 (.pad(dac_data_o[3]), .c2p(dac_data_o_core[3]));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_4 (.pad(dac_data_o[4]), .c2p(dac_data_o_core[4]));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_5 (.pad(dac_data_o[5]), .c2p(dac_data_o_core[5]));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_6 (.pad(dac_data_o[6]), .c2p(dac_data_o_core[6]));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_7 (.pad(dac_data_o[7]), .c2p(dac_data_o_core[7]));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_8 (.pad(dac_data_o[8]), .c2p(dac_data_o_core[8]));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_9 (.pad(dac_data_o[9]), .c2p(dac_data_o_core[9]));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_10 (.pad(dac_data_o[10]), .c2p(dac_data_o_core[10]));
  (* keep *) sg13g2_IOPadOut4mA pad_dac_data_o_11 (.pad(dac_data_o[11]), .c2p(dac_data_o_core[11]));
  (* keep *) sg13g2_IOPadVdd pad_vdd_n ();
  (* keep *) sg13g2_IOPadVss pad_vss_n ();
  (* keep *) sg13g2_IOPadIOVdd pad_iovdd_n ();
  (* keep *) sg13g2_IOPadIOVss pad_iovss_n ();
  (* keep *) sg13g2_IOPadIn pad_ref_clk_i (.pad(ref_clk_i), .p2c(ref_clk_i_core));
  (* keep *) sg13g2_IOPadIn pad_ref_rst_ni (.pad(ref_rst_ni), .p2c(ref_rst_ni_core));
  // ---- WEST row (listed west->east / south->north) ----
  (* keep *) sg13g2_IOPadOut4mA pad_atest_en_o (.pad(atest_en_o), .c2p(atest_en_o_core));
  (* keep *) sg13g2_IOPadOut4mA pad_atest_sel_o_0 (.pad(atest_sel_o[0]), .c2p(atest_sel_o_core[0]));
  (* keep *) sg13g2_IOPadOut4mA pad_atest_sel_o_1 (.pad(atest_sel_o[1]), .c2p(atest_sel_o_core[1]));
  (* keep *) sg13g2_IOPadOut4mA pad_atest_sel_o_2 (.pad(atest_sel_o[2]), .c2p(atest_sel_o_core[2]));
  (* keep *) sg13g2_IOPadOut4mA pad_atest_sel_o_3 (.pad(atest_sel_o[3]), .c2p(atest_sel_o_core[3]));
  (* keep *) sg13g2_IOPadIn pad_ana_flag_i_0 (.pad(ana_flag_i[0]), .p2c(ana_flag_i_core[0]));
  (* keep *) sg13g2_IOPadIn pad_ana_flag_i_1 (.pad(ana_flag_i[1]), .p2c(ana_flag_i_core[1]));
  (* keep *) sg13g2_IOPadIn pad_ana_flag_i_2 (.pad(ana_flag_i[2]), .p2c(ana_flag_i_core[2]));
  (* keep *) sg13g2_IOPadIn pad_ana_flag_i_3 (.pad(ana_flag_i[3]), .p2c(ana_flag_i_core[3]));
  (* keep *) sg13g2_IOPadVdd pad_vdd_w ();
  (* keep *) sg13g2_IOPadVss pad_vss_w ();
  (* keep *) sg13g2_IOPadOut4mA pad_adc_start_o (.pad(adc_start_o), .c2p(adc_start_o_core));
  (* keep *) sg13g2_IOPadOut4mA pad_adc_ch_o_0 (.pad(adc_ch_o[0]), .c2p(adc_ch_o_core[0]));
  (* keep *) sg13g2_IOPadOut4mA pad_adc_ch_o_1 (.pad(adc_ch_o[1]), .c2p(adc_ch_o_core[1]));
  (* keep *) sg13g2_IOPadOut4mA pad_adc_ch_o_2 (.pad(adc_ch_o[2]), .c2p(adc_ch_o_core[2]));
  (* keep *) sg13g2_IOPadIn pad_adc_valid_i (.pad(adc_valid_i), .p2c(adc_valid_i_core));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_0 (.pad(adc_data_i[0]), .p2c(adc_data_i_core[0]));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_1 (.pad(adc_data_i[1]), .p2c(adc_data_i_core[1]));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_2 (.pad(adc_data_i[2]), .p2c(adc_data_i_core[2]));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_3 (.pad(adc_data_i[3]), .p2c(adc_data_i_core[3]));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_4 (.pad(adc_data_i[4]), .p2c(adc_data_i_core[4]));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_5 (.pad(adc_data_i[5]), .p2c(adc_data_i_core[5]));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_6 (.pad(adc_data_i[6]), .p2c(adc_data_i_core[6]));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_7 (.pad(adc_data_i[7]), .p2c(adc_data_i_core[7]));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_8 (.pad(adc_data_i[8]), .p2c(adc_data_i_core[8]));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_9 (.pad(adc_data_i[9]), .p2c(adc_data_i_core[9]));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_10 (.pad(adc_data_i[10]), .p2c(adc_data_i_core[10]));
  (* keep *) sg13g2_IOPadIn pad_adc_data_i_11 (.pad(adc_data_i[11]), .p2c(adc_data_i_core[11]));
  (* keep *) sg13g2_IOPadIOVdd pad_iovdd_w ();
  (* keep *) sg13g2_IOPadIOVss pad_iovss_w ();

  cdriscv_subsys #(.BootEnable(1'b1)) u_sub (
      .clk_i           (clk_i_core),
      .rst_ni          (rst_ni_core),
      .ref_clk_i       (ref_clk_i_core),
      .ref_rst_ni      (ref_rst_ni_core),
      .boot_addr_i     (32'h0000_0000),
      .fetch_enable_i  (fetch_enable_i_core),
      .irq_i           (irq_i_core),
      .fault_ext_i     (fault_ext_i_core),
      .err_pin_o       (err_pin_o_core),
      .reset_req_o     (reset_req_o_core),
      .fault_any_o     (fault_any_o_core),
      .adc_start_o     (adc_start_o_core),
      .adc_ch_o        (adc_ch_o_core),
      .adc_valid_i     (adc_valid_i_core),
      .adc_data_i      (adc_data_i_core),
      .dac_data_o      (dac_data_o_core),
      .dac_we_o        (dac_we_o_core),
      .atest_en_o      (atest_en_o_core),
      .atest_sel_o     (atest_sel_o_core),
      .ana_flag_i      (ana_flag_i_core),
      .ext_psel_o      (),
      .ext_penable_o   (),
      .ext_paddr_o     (),
      .ext_pwrite_o    (),
      .ext_pwdata_o    (),
      .ext_pstrb_o     (),
      .ext_prdata_i    (32'h0000_0000),
      .ext_pready_i    (1'b1),
      .ext_pslverr_i   (1'b0),
      .core_sleep_o    (core_sleep_o_core),
      .retire_valid_o  (),
      .retire_pc_o     (),
      .retire_instr_o  (),
      .qspi_sclk_o     (qspi_sclk_o_core),
      .qspi_cs_no      (qspi_cs_no_core),
      .qspi_io_i       (qspi_io_i_core),
      .qspi_io_o       (qspi_io_o_core),
      .qspi_io_oe_o    (qspi_io_oe_o_core)
  );

endmodule
`default_nettype wire
